### ISSUE TITLE
Prevents sails from loading in interactive mode

### ISSUE THREAD

**Issue by ronenteva** [gayanhewa/sailsjs-cacheman#1] opened 2015-08-30 08:46 UTC
When running `sails console` the following error occurs:

```
config = Sails.config.cacheman;
                     ^
TypeError: Cannot read property 'cacheman' of undefined
    at Object.Cache [as sailsCacheman] (...\node_modules\sailsjs-cacheman\lib\sailsCacheman.js:12:25)
```

`sails lift` works fine

**Comment by gayanhewa** [comment] 2015-09-05 03:07
@ronenteva I am attempting to replicate this issue. Can you send me a pull request with the code to replicate the bug , I am not able to replicate the same.

Also , make sure the config/cacheman.js is located correctly.

**Comment by ronenteva** [comment] 2015-09-05 05:51
conifg/cacheman.js is located correctly, it's content is:

```
module.exports.cacheman = {
  driver: 'redis',

  memory: {
    engine: 'cacheman-memory'
  },

  redis: {
    port: 6379,
    host: '127.0.0.1',
    database: 0,
    engine: 'cacheman-redis'
  }
};
```

I keep getting that error in my project, but I tried replicating it into a new project and it seems to be working fine. 
Perhaps it's conflicting with some other package I have installed?

**Comment by gayanhewa** [comment] 2015-09-05 05:53
Possible. Difficult address the issue without being able to reproduce. Anyways  , if you come across it again , do send a pull request with the code to reproduce it or steps and will take it from there.

**Comment by michael-tomala** [comment] 2016-07-25 15:51
I have the same issue. I think that problem is in `sailsCacheman.js` with `var Sails = require('sails')`   #
When sails.lift it is ok, but crash when sails.load.
http://sailsjs.org/documentation/reference/application/sails-load
I read configuration from sails.config.cacheman (lowercase 's') it works. 
Figure out the problem, when I started using `sails-db-migrate`.

**Comment by gayanhewa** [comment] 2016-07-25 15:54
@michael-tomala can you replicate the issue ? If can provide me a pull request we can figure out a solution

**Comment by michael-tomala** [comment] 2016-07-25 16:01
I have some problem with pull request :), I don't have permissions?
![image](https://cloud.githubusercontent.com/assets/19348836/17107958/b7d7fc20-5291-11e6-9315-ab8ca9eaf3ba.png)

**Comment by gayanhewa** [comment] 2016-07-25 16:09
@michael-tomala looks like you are pushing to the original repo. Try to fork the original repo then push to ur branch and initiate a pull request.

https://help.github.com/articles/using-pull-requests/

**Comment by michael-tomala** [comment] 2016-07-25 17:25
Ok, I have created pull request.

**Comment by gayanhewa** [comment] 2017-04-30 13:32
Merged https://github.com/gayanhewa/sailsjs-cacheman/pull/6

**Closed as completed by gayanhewa** 2017-04-30 13:32 UTC
Labels: bug, help wanted
